const GET_BILLS = 'GET_BILLS';
const GET_BILLS_SUCCESS = 'GET_BILLS_SUCCESS';
const GET_BILLS_ERROR = 'GET_BILLS_ERROR';

const DELETE_BILL = 'DELETE_BILL';
const UPDATE_BILL = 'UPDATE_BILL';

export {
  GET_BILLS,
  GET_BILLS_SUCCESS,
  GET_BILLS_ERROR,
  DELETE_BILL,
  UPDATE_BILL,
};